### PR TITLE
Refs #7126 Fixes ctest.

### PR DESCRIPTION
**Pull request by LuisGP**

### CODE REVIEW

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/xtypes-manual-linux/47/)

**Comment by LuisGP** [comment]
Jenkins failed due to generator-parser roundtrip and lack of ctest yet.

**Comment by LuisGP** [comment]
> Jenkins failed due to generator-parser roundtrip and lack of ctest yet.

Jenkins updated.

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/xtypes-manual-linux/48/)

**Review by lemunozm — APPROVED** [review]

**Pull request merged**
