### PR TITLE
Feature/char16 t support [8225]

### PR DESCRIPTION
**Pull request by LuisGP**
This PR adds support for `char16_t` and `u16string` types.

It adds a new `String16Type` type.

### CODE REVIEW

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/xtypes-manual-linux/130/)

**Comment by jamoralp** [comment]
Consider adding test cases for char16_t in `test/unitary/xtypes/dynamicdata_operators.cpp` test file.

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/xtypes-manual-linux/131/)

**Review by jamoralp — APPROVED** [review]
LGTM

**Pull request merged**
